embed_assets: on

javascripts:
  workspace:
    #include jquery from google, as likely the user will have this precached
    - public/javascripts/jquery_ujs.js #Renamed rails.js for jquery
    - public/javascripts/application.js

stylesheets:
  common:
    - public/stylesheets/blueprint/screen.css
    - public/stylesheets/global.css
    - public/stylesheets/formtastic.css
    - public/stylesheets/formtastic_changes.css

