development:
  username: postgres
  adapter: postgresql
  database: bandsite_development
  password: postgres

test:
  username: postgres
  adapter: postgresql
  database: bandsite_test
  password: postgres

production:
  username: postgres
  adapter: postgresql
  database: bandsite_production
  password: postgres
