development:
  adapter: postgresql
  username: th3james
  host: localhost
  database: bandsite_development

test:
  username: th3james
  adapter: postgresql
  database: bandsite_test
  host: localhost

production:
  username: postgres
  adapter: postgresql
  database: bandsite_production
  password: postgres
